config/routes.rb
Rails.application.routes.draw do
  root 'pages#one'

  get 'pages/one'

  get 'pages/two'
  
  get 'pages/three'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">Navbar</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
			  <li class="nav-item active">
			    <%= link_to("Page one", pages_one_path, class: "nav-link") %>
			  </li>
			  <li class="nav-item">
			    <%= link_to("Page two", pages_two_path, class: "nav-link") %>
			  </li>
			  <li class="nav-item">
			    <%= link_to("Page three", pages_three_path, class: "nav-link") %>
			  </li>
			</ul>
		</div>
	</nav>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>

</html>

app/views/pages/one.html.erb
<h1>Daniela A. Venegas Navarrete</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2>Título</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt, eius commodi dolor soluta mollitia facere possimus ut expedita explicabo quibusdam nihil hic odit. Nemo reiciendis reprehenderit repudiandae, vel, cum autem.</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>
<%= image_tag("captura.jpg") %>